
[types]

	[types.cut_blocK_type]

		[types.cut_blocK_type.supplementaries]
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_blocK_type.darkerdepths]
			petrified = true
			shale = true
			polished_shale = true
			shale_bricks = true
			aridrock = true
			polished_aridrock = true
			aridrock_bricks = true
			limestone = true
			polished_limestone = true
			limestone_bricks = true
			grimestone = true
			polished_grimestone = true
			grimestone_bricks = true

		[types.cut_blocK_type.framedblocks]
			framed_slope = true
			framed_double_slope = true
			framed_pyramid = true

		[types.cut_blocK_type.pneumaticcraft]
			reinforced_stone = true
			compressed_stone = true

		[types.cut_blocK_type.biomesoplenty]
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			orange_sandstone = true
			smooth_orange_sandstone = true
			cut_orange_sandstone = true
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.cut_blocK_type.domum_ornamentum]
			shingle = true

		[types.cut_blocK_type.ecologics]
			coconut = true
			walnut = true
			azalea = true
			flowering_azalea = true

		[types.cut_blocK_type.integrateddynamics]
			menril = true
			crystalized_menril_block = true
			crystalized_menril_brick = true
			crystalized_chorus_block = true
			crystalized_chorus_brick = true

		[types.cut_blocK_type.ad_astra]
			iron_plating = true
			steel_plating = true
			desh_plating = true
			ostrum_plating = true
			calorite_plating = true
			moon_stone = true
			moon_cobblestone = true
			polished_moon_stone = true
			aeronos = true
			strophar = true
			mars_stone = true
			mars_cobblestone = true
			polished_mars_stone = true
			mercury_stone = true
			mercury_cobblestone = true
			polished_mercury_stone = true
			venus_stone = true
			venus_cobblestone = true
			polished_venus_stone = true
			glacio_stone = true
			glacio_cobblestone = true
			polished_glacio_stone = true
			polished_permafrost = true
			glacian = true

		[types.cut_blocK_type.create_things_and_misc]
			brass_tiles = true

		[types.cut_blocK_type.blue_skies]
			nature_stone = true
			glowing_nature_stone = true
			nature_stonebrick = true
			glowing_nature_stonebrick = true
			poison_stone = true
			glowing_poison_stone = true
			poison_stonebrick = true
			rough_poison_stonebrick = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true
			crystallized = true
			turquoise_stone = true
			turquoise_cobblestone = true
			mossy_turquoise_cobblestone = true
			turquoise_stonebrick = true
			mossy_turquoise_stonebrick = true
			cracked_turquoise_stonebrick = true
			midnight_sandstone = true
			smooth_midnight_sandstone = true
			brumble = true
			polished_brumble = true
			taratite = true
			polished_taratite = true
			rimestone = true
			polished_rimestone = true
			lunar_stone = true
			lunar_cobblestone = true
			mossy_lunar_cobblestone = true
			lunar_stonebrick = true
			mossy_lunar_stonebrick = true
			cracked_lunar_stonebrick = true
			crystal_sandstone = true
			smooth_crystal_sandstone = true
			cut_midnight_sandstone = true
			cut_crystal_sandstone = true
			umber = true
			polished_umber = true
			cinderstone = true
			polished_cinderstone = true

		[types.cut_blocK_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.cut_blocK_type.mekanismadditions]
			black_plastic = true
			black_plastic_glow = true
			black_plastic_transparent = true
			blue_plastic = true
			blue_plastic_glow = true
			blue_plastic_transparent = true
			green_plastic = true
			green_plastic_glow = true
			green_plastic_transparent = true
			cyan_plastic = true
			cyan_plastic_glow = true
			cyan_plastic_transparent = true
			dark_red_plastic = true
			dark_red_plastic_glow = true
			dark_red_plastic_transparent = true
			purple_plastic = true
			purple_plastic_glow = true
			purple_plastic_transparent = true
			orange_plastic = true
			orange_plastic_glow = true
			orange_plastic_transparent = true
			light_gray_plastic = true
			light_gray_plastic_glow = true
			light_gray_plastic_transparent = true
			gray_plastic = true
			gray_plastic_glow = true
			gray_plastic_transparent = true
			light_blue_plastic = true
			light_blue_plastic_glow = true
			light_blue_plastic_transparent = true
			lime_plastic = true
			lime_plastic_glow = true
			lime_plastic_transparent = true
			aqua_plastic = true
			aqua_plastic_glow = true
			aqua_plastic_transparent = true
			red_plastic = true
			red_plastic_glow = true
			red_plastic_transparent = true
			magenta_plastic = true
			magenta_plastic_glow = true
			magenta_plastic_transparent = true
			yellow_plastic = true
			yellow_plastic_glow = true
			yellow_plastic_transparent = true
			white_plastic = true
			white_plastic_glow = true
			white_plastic_transparent = true
			brown_plastic = true
			brown_plastic_glow = true
			brown_plastic_transparent = true
			pink_plastic = true
			pink_plastic_glow = true
			pink_plastic_transparent = true

		[types.cut_blocK_type.ars_nouveau]
			archwood = true

		[types.cut_blocK_type.sullysmod]
			smoothed_rough_jade = true

		[types.cut_blocK_type.create]
			cut_granite = true
			polished_cut_granite = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_veridium = true
			polished_cut_veridium = true

		[types.cut_blocK_type.createdeco]
			worn_bricks = true
			worn_brick_tiles = true
			worn_long_bricks = true
			worn_short_bricks = true
			cracked_worn_bricks = true
			cracked_worn_brick_tiles = true
			cracked_worn_long_bricks = true
			cracked_worn_short_bricks = true
			mossy_worn_bricks = true
			mossy_worn_brick_tiles = true
			mossy_worn_long_bricks = true
			mossy_worn_short_bricks = true
			red_brick_tiles = true
			red_long_bricks = true
			red_short_bricks = true
			cracked_red_bricks = true
			cracked_red_brick_tiles = true
			cracked_red_long_bricks = true
			cracked_red_short_bricks = true
			mossy_red_bricks = true
			mossy_red_brick_tiles = true
			mossy_red_long_bricks = true
			mossy_red_short_bricks = true
			dean_bricks = true
			dean_brick_tiles = true
			dean_long_bricks = true
			dean_short_bricks = true
			cracked_dean_bricks = true
			cracked_dean_brick_tiles = true
			cracked_dean_long_bricks = true
			cracked_dean_short_bricks = true
			mossy_dean_bricks = true
			mossy_dean_brick_tiles = true
			mossy_dean_long_bricks = true
			mossy_dean_short_bricks = true
			pearl_bricks = true
			pearl_brick_tiles = true
			pearl_long_bricks = true
			pearl_short_bricks = true
			cracked_pearl_bricks = true
			cracked_pearl_brick_tiles = true
			cracked_pearl_long_bricks = true
			cracked_pearl_short_bricks = true
			mossy_pearl_bricks = true
			mossy_pearl_brick_tiles = true
			mossy_pearl_long_bricks = true
			mossy_pearl_short_bricks = true
			dusk_bricks = true
			dusk_brick_tiles = true
			dusk_long_bricks = true
			dusk_short_bricks = true
			cracked_dusk_bricks = true
			cracked_dusk_brick_tiles = true
			cracked_dusk_long_bricks = true
			cracked_dusk_short_bricks = true
			mossy_dusk_bricks = true
			mossy_dusk_brick_tiles = true
			mossy_dusk_long_bricks = true
			mossy_dusk_short_bricks = true
			blue_bricks = true
			blue_brick_tiles = true
			blue_long_bricks = true
			blue_short_bricks = true
			cracked_blue_bricks = true
			cracked_blue_brick_tiles = true
			cracked_blue_long_bricks = true
			cracked_blue_short_bricks = true
			mossy_blue_bricks = true
			mossy_blue_brick_tiles = true
			mossy_blue_long_bricks = true
			mossy_blue_short_bricks = true
			scarlet_bricks = true
			scarlet_brick_tiles = true
			scarlet_long_bricks = true
			scarlet_short_bricks = true
			cracked_scarlet_bricks = true
			cracked_scarlet_brick_tiles = true
			cracked_scarlet_long_bricks = true
			cracked_scarlet_short_bricks = true
			mossy_scarlet_bricks = true
			mossy_scarlet_brick_tiles = true
			mossy_scarlet_long_bricks = true
			mossy_scarlet_short_bricks = true

		[types.cut_blocK_type.create_confectionery]
			chocolate_bricks = true
			black_chocolate_bricks = true
			white_chocolate_bricks = true
			caramel_bricks = true

		[types.cut_blocK_type.immersiveengineering]
			sheetmetal_copper = true
			sheetmetal_aluminum = true
			storage_aluminum = true
			sheetmetal_lead = true
			storage_lead = true
			sheetmetal_silver = true
			storage_silver = true
			sheetmetal_nickel = true
			storage_nickel = true
			sheetmetal_uranium = true
			storage_uranium = true
			sheetmetal_constantan = true
			storage_constantan = true
			sheetmetal_electrum = true
			storage_electrum = true
			sheetmetal_steel = true
			storage_steel = true
			sheetmetal_iron = true
			sheetmetal_gold = true
			treated_wood_horizontal = true
			treated_wood_vertical = true
			treated_wood_packaged = true
			sheetmetal_colored_white = true
			sheetmetal_colored_orange = true
			sheetmetal_colored_magenta = true
			sheetmetal_colored_light_blue = true
			sheetmetal_colored_yellow = true
			sheetmetal_colored_lime = true
			sheetmetal_colored_pink = true
			sheetmetal_colored_gray = true
			sheetmetal_colored_light_gray = true
			sheetmetal_colored_cyan = true
			sheetmetal_colored_purple = true
			sheetmetal_colored_blue = true
			sheetmetal_colored_brown = true
			sheetmetal_colored_green = true
			sheetmetal_colored_red = true
			sheetmetal_colored_black = true
			steel_scaffolding_standard = true
			alu_scaffolding_standard = true
			steel_scaffolding_grate_top = true
			alu_scaffolding_grate_top = true
			steel_scaffolding_wooden_top = true
			alu_scaffolding_wooden_top = true
			cokebrick = true
			blastbrick = true
			blastbrick_reinforced = true
			coke = true
			hempcrete = true
			concrete = true
			concrete_tile = true
			concrete_leaded = true
			insulating_glass = true
			alloybrick = true

		[types.cut_blocK_type.ae2]
			sky_stone_brick = true
			sky_stone_small_brick = true
			smooth_quartz = true
			quartz_pillar = true

		[types.cut_blocK_type.quark]
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			iron_plate = true
			rusty_iron_plate = true
			azalea_planks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			blossom_planks = true
			permafrost = true
			permafrost_bricks = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true
			midori_block = true
			thatch = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			duskbound_block = true

		[types.cut_blocK_type.engineersdecor]
			rebar_concrete = true
			rebar_concrete_tile = true
			dark_shingle_roof = true
			old_industrial_wood = true

		[types.cut_blocK_type.cave_enhancements]
			polished_rose_quartz = true

		[types.cut_blocK_type.neapolitan]
			frond_thatch = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.blue_skies]
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true
			crescent_fruit = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			red_archwood = true
			green_archwood = true
			purple_archwood = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			blossom = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.blue_skies]
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

	[entries.wood_type]

		[entries.wood_type.woodworks]
			bookshelf = true
			boards = true
			ladder = true
			beehive = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

